#!/usr/bin/env bash
# Overnight autonomous pipeline — run via nohup. Gets the tool ready for morning paper trading:
#   1. wait for the running 5y gap-fill to finish
#   2. straggler sweeps until coverage stops growing (skip_existing = only re-fetch the misses)
#   3. train the ML scorer on the REAL 5-year corpus
#   4. verify paper-trading (synthetic backtest) + a real-archive leaderboard sanity check
#   5. write logs/MORNING_REPORT.md
# Idempotent and best-effort: a failed step is logged and the rest still run.

set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"; cd "$REPO"
PY="$REPO/.venv/bin/python"
LOG="$REPO/logs/overnight.log"; RPT="$REPO/logs/MORNING_REPORT.md"
mkdir -p "$REPO/logs"
say(){ echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG"; }
nsym(){ ls "$REPO/data/parquet" 2>/dev/null | grep -c "symbol=" || echo 0; }

say "=== OVERNIGHT START (pid $$) ==="

# 1) Wait for any running backfill/gap-fill to finish.
for pid in $(pgrep -f "cli backfill" || true); do
  say "waiting for backfill pid $pid ..."
  while kill -0 "$pid" 2>/dev/null; do sleep 60; done
done
say "backfill idle. archived symbols: $(nsym)"

# 2) Straggler sweeps until coverage plateaus (max 4 passes).
prev=0
for pass in 1 2 3 4; do
  cur=$(nsym)
  say "sweep $pass start (symbols=$cur)"
  "$PY" -m signal_engine.cli backfill --years 5 --workers 3 >>"$LOG" 2>&1 \
    || say "sweep $pass returned non-zero"
  cur2=$(nsym)
  say "sweep $pass done (symbols=$cur2)"
  if [ "$cur2" -le "$prev" ] && [ "$pass" -gt 1 ]; then say "coverage plateaued"; break; fi
  prev=$cur2
done
say "backfill final coverage: $(nsym) symbols"

# 3) Train the ML scorer on the real corpus (most-liquid 400 names).
say "training ML on real 5y archive ..."
"$PY" -m signal_engine.cli train --source archive --max-symbols 400 --stride 3 \
    --out "$REPO/data/models/signal_model.json" >"$REPO/logs/ml_train.out" 2>>"$LOG" \
    && say "ML training done" || say "ML training FAILED (see logs/ml_train.out)"

# 4) Verify paper trading (synthetic backtest is the deterministic machinery check).
say "verifying paper-trading backtest ..."
"$PY" -m signal_engine.cli backtest --days 20 >"$REPO/logs/backtest.out" 2>>"$LOG" \
    || say "backtest errored"

# 5) Assemble the morning report.
{
  echo "# Morning Report — $(date '+%Y-%m-%d %H:%M %Z')"
  echo
  echo "## Data (5-year backfill)"
  echo "- Archived symbols: **$(nsym)** (target ~2,091 NSE EQ)"
  echo "- Corpus size: **$(du -sh "$REPO/data/parquet" 2>/dev/null | cut -f1)**"
  echo
  echo "## ML model (trained on REAL archive)"
  echo '```'
  grep -E "samples|base rate|out-of-sample|AUC gain|top features|Model saved" "$REPO/logs/ml_train.out" 2>/dev/null | tail -8
  echo '```'
  echo
  echo "## Paper-trading backtest (synthetic machinery check)"
  echo '```'
  grep -E "days|win rate|profit factor|expectancy|total net|Sharpe|Strategy Health" "$REPO/logs/backtest.out" 2>/dev/null | tail -8
  echo '```'
  echo
  echo "## Services"
  echo "- Scheduler: $(pgrep -f 'cli schedule' >/dev/null && echo RUNNING || echo NOT RUNNING)"
  echo "- API+tunnel: $(pgrep -f 'cli serve' >/dev/null && echo RUNNING || echo NOT RUNNING)"
  echo "- Dashboard: https://web-beta-beige-60.vercel.app"
  echo
  echo "_Generated by scripts/overnight.sh. Decision-support only; paper trades, no live orders._"
} > "$RPT" 2>>"$LOG"

say "=== OVERNIGHT COMPLETE -> $RPT ==="
